# Generated by Django 3.2.8 on 2021-10-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterCredentials',
            fields=[
                ('token_id', models.AutoField(primary_key=True, serialize=False)),
                ('influencer_id', models.IntegerField(unique=True)),
                ('profile_id', models.IntegerField(db_index=True)),
                ('oauth_token', models.CharField(default=None, max_length=512, null=True)),
                ('oauth_token_secret', models.CharField(default=None, max_length=512, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=None, null=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'twitter_access_token',
            },
        ),
    ]
